--- 
jobs: 
  build: 
    runs-on: ubuntu-latest
  steps: 
    - 
      name: Checkout
      uses: actions/checkout@v1
    - 
      name: "Install and build"
      run: "npm install && npm run build"
    - 
      name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with: 
        branch: gh-pages
        folder: build
  strategy: 
    matrix: 
      node_version: 
        - 15.x
name: "Github Pages Deploy"
true: 
  push: 
    branches: 
      - master
